### ISSUE TITLE
Steamid Copy Bug

### ISSUE THREAD

**Issue by ghost** [avi12/steam-id-finder#3]
hello, so i want to copy only steamid but it copied steamid, steamid 32 and steamid 64.

example : 
1. i want copy "STEAM_0:0:84111"
2. but when i CTRL + V it become "STEAM_0:0:84111 // Test( https://steamcommunity.com/profiles/76561197960433950 )

**Comment by avi12** [comment]
That's not a bug, that's a feature
To get rid of the trailing `// Test ...`,  open the popup page and uncheck `ID e.g. STEAM_X:Y:ZZZZ`

**Comment by ghost** [comment]
Thank you! didn't know about that before
