### ISSUE TITLE
[Bug] Profile URL with a trailing `/` won't display IDs

### ISSUE THREAD

**Issue by cactus918** [avi12/steam-id-finder#6]
### Describe the bug

the ID's do not appear on the steam profile page

### How to reproduce

When the steam profile URL has a '/' at the end the IDs don't appear.

![screenshot works](https://cdn.discordapp.com/attachments/1039157754406903878/1052336400558719017/image.png)
![screenshot broken](https://cdn.discordapp.com/attachments/1039157754406903878/1052336595606437888/image.png)

You can fix the issue by simply removing the slash and clicking enter.

### Expected behavior

The steam IDs should ideally appear

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

Windows

### What's the version you're running?

1.0.0

### Additional context

I am charlie from the email
Profile: [Wanna_Cry](https://steamcommunity.com/id/Wanna_Cry)

**Comment by avi12** [comment]
Seems like my RegExp was not quite right
https://github.com/avi12/steam-id-finder/blob/34553404393bd35d6aa1ccad6253e19d893b8beb/src/types/steam-page.model.ts#L5

**Comment by cactus918** [comment]
Sweet! Thanks for the quick response time! Love to see developers who are active 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
